using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatEventAction : Object
        {
            /// <summary>
            /// A voice chat participant volume level was changed
            /// </summary>
            public class ChatEventVoiceChatParticipantVolumeLevelChanged : ChatEventAction
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatEventVoiceChatParticipantVolumeLevelChanged";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

/// <summary>
/// Identifier of the affected group call participant
/// </summary>
[JsonConverter(typeof(Converter))]
[JsonProperty("participant")]
public MessageSender Participant { get; set; }

/// <summary>
/// New value of volume_level; 1-20000 in hundreds of percents
/// </summary>
[JsonConverter(typeof(Converter))]
[JsonProperty("volume_level")]
public int VolumeLevel { get; set; }


            }
        }
    }
}
