using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class GroupCallJoinResponse : Object
        {
            /// <summary>
            /// Describes a group call join response
            /// </summary>
            public class GroupCallJoinResponseWebrtc : GroupCallJoinResponse
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "groupCallJoinResponseWebrtc";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

/// <summary>
/// Group call payload to pass to tgcalls
/// </summary>
[JsonConverter(typeof(Converter))]
[JsonProperty("payload")]
public GroupCallPayload Payload { get; set; }

/// <summary>
/// Join response candidates to pass to tgcalls
/// </summary>
[JsonConverter(typeof(Converter))]
[JsonProperty("candidates")]
public GroupCallJoinResponseCandidate[] Candidates { get; set; }


            }
        }
    }
}
