namespace TdLib
{
    using System.Threading.Tasks;

    using Newtonsoft.Json;

    /// <summary>Autogenerated TDLib APIs</summary>
    public static partial class TdApi
    {
        /// <summary>Creates a new invite link for a chat. Available for basic groups, supergroups,
        /// and channels. Requires administrator privileges and can_invite_users right in the chat</summary>
        public static Task<ChatInviteLink> CreateChatInviteLinkAsync(this Client client, long chatId = default, int expireDate = default, int memberLimit = default)
        {
            return client.ExecuteAsync(new CreateChatInviteLink { ChatId = chatId, ExpireDate = expireDate, MemberLimit = memberLimit });
        }

        /// <summary>Creates a new invite link for a chat. Available for basic groups, supergroups,
        /// and channels. Requires administrator privileges and can_invite_users right in the chat</summary>
        public class CreateChatInviteLink : Function<ChatInviteLink>
        {
            /// <summary>Data type for serialization</summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "createChatInviteLink";

            /// <summary>Extra data attached to the function</summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>Chat identifier</summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>Point in time (Unix timestamp) when the link will expire; pass 0 if never</summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("expire_date")]
            public int ExpireDate { get; set; }

            /// <summary>Maximum number of chat members that can join the chat by the link
            /// simultaneously; 0-99999; pass 0 if not limited</summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("member_limit")]
            public int MemberLimit { get; set; }
        }
    }
}